domains = [{
    'description': '(mdp18) Red-finned Blue-Eye:\n\nsubmitted by Iadine Chades and Thomas Keller.\n\nDescription: Red-finned blue-eye (Scaturiginichthys vermeilipinnis) are a species of fish that are endemic to seven artesian springs in the Edgbaston Reserve in Central Queensland, Australia. The species is critically endangered due to competition by the invasive eastern mosquitofish (Gambusia holbrooki).\n The Red-finned Blue-eye domain tackles the problem of eradicating the invasive Gambusia from the habitat of the red-finned blue-eye. The springs are disconnected during the dry season, but get connected in the rain season which allows the Gambusia population to spread from spring to spring and replace the red-finned blue-eyes.\n To prevent the extinction of the red-finned blue-eye species, springs with Gambusia population can be poisened (with a high success probability but a penalty for using poison), the Gambusia population can be removed manually (with a lower probability of success and more required effort, but without incurring a penalty) or red-finned blue-eyes can be translocated to a spring without any fish population (which takes so much effort that it can only be done once every few years).\n The Red-finned Blue-eye domain is based on the following paper: \n Sam Nicol, Regis Sabbadin, Nathalie Peyrard and Iadine Chades: "Finding the best management policy to eradicate invasive species from spatial ecological networks with simultaneous actions". Journal of Applied Ecology, 2017.',
    'ipc': '2018',
    'name': 'red-finned-blue-eye',
    'problems': [('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__01.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__02.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__03.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__04.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__05.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__06.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__07.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__08.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__09.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__10.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__11.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__12.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__13.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__14.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__15.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__16.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__17.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__18.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__19.rddl'),
                 ('red-finned-blue-eye-mdp-2018/red-finned-blue-eye_mdp.rddl', 'red-finned-blue-eye-mdp-2018/red-finned-blue-eye_inst_mdp__20.rddl')]}]
