domains = [{
    'description': '(mdp18) Push Your Luck:\n\nsubmitted by Thomas Keller.\n\nDescription: As the name suggest, Push Your Luck is an artificial version of a "push your luck" game like, for instance, Can\'t Stop (see http://boardgamegeek.com/boardgame/41/cant-stop for more information). The main challenge of push your luck games is to determine the optimal moment to stop a repeated stochastic process.\n In case of the Push Your Luck domain, the player may roll one or more dice repeatedly. Each rolled face is marked if it hasn\'t been marked before, and all numbers are unmarked if the player chooses to cash out its reward, if a number is rolled that is already marked or if two rolled dice come up the same face.\n The reward the player obtaines upon cashing out corresponds to the product over the value of all marked faces, so it grows exponentially in the number of consecutive die rolls (by default, the value of the face of a 6-sided die equals half the number shown on the die, and the default value of a 10- or 20-sided die is 0.25 plus a quarter of the shown die value. On the other hand, the probability to hit a previously rolled number increases with the number of consecutive die rolls.',
    'ipc': '2018',
    'name': 'push-your-luck',
    'problems': [('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__01.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__02.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__03.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__04.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__05.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__06.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__07.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__08.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__09.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__10.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__11.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__12.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__13.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__14.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__15.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__16.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__17.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__18.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__19.rddl'),
                 ('push-your-luck-mdp-2018/push-your-luck_mdp.rddl', 'push-your-luck-mdp-2018/push-your-luck_inst_mdp__20.rddl')]}]
