domains = [{
    'description': '(mdp18) Earth Observation:\n\nsubmitted by Thomas Keller (based on the KI 2014 paper "An Experimental Comparison of Classical, FOND and Probabilistic Planning" by Andreas Hertle, Christian Dornhege, Thomas Keller, Robert Mattmüller, Manuela Ortlieb, and Bernhard Nebel).\n\nDescription: The Earth Observation domain models a satellite orbiting Earth. It can take pictures of the landscape below with a camera. The landscape is subdivided into square regions of interest forming a grid wrapped around a cylindrical projection of the Earth surface. The camera focuses on one region at a time and can be shifted north or south. It can take a picture of the region currently in focus. The focus may not be shifted while taking a picture.\n Regardless whether the focus is shifted or a picture is taken, the satellite moves eastward around Earth, shifting the focus one grid cell to the east in addition to the other effects in each step. The objective is to take pictures of certain regions in a limited timeframe with as few shifts and as quick as possible. Taking a picture of a region does not guarantee good image quality: the worse the weather, the lower the chance of success./n Over time the visibility in each region can change probabilistically. Changes between similar levels of visibility are more likely than vast changes.',
    'ipc': '2018',
    'name': 'earth-observation',
    'problems': [('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__01.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__02.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__03.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__04.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__05.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__06.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__07.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__08.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__09.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__10.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__11.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__12.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__13.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__14.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__15.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__16.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__17.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__18.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__19.rddl'),
                 ('earth-observation-mdp-2018/earth-observation_mdp.rddl', 'earth-observation-mdp-2018/earth-observation_inst_mdp__20.rddl')]}]
