domains = [{
    'description': '(mdp18) Academic Advising:\n\submitted by Thomas Keller (based on the Academic Advising domain submitted by Libby Ferland and Scott Sanner for IPC 2014).\n\nDescription: In this domain, a student may take courses at a given cost and passes the course with a probability determined by how many of the prerequisites they have successfully passed. A student also receives a penalty at each time step if they have not yet graduated from their program (i.e., completed all required courses).  We allow multiple courses to be taken in a semester in some instances.',
    'ipc': '2018',
    'name': 'academic-advising',
    'problems': [('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__01.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__02.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__03.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__04.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__05.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__06.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__07.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__08.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__09.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__10.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__11.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__12.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__13.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__14.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__15.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__16.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__17.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__18.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__19.rddl'),
                 ('academic-advising-mdp-2018/academic-advising_mdp.rddl', 'academic-advising-mdp-2018/academic-advising_inst_mdp__20.rddl')]}]
