domains = [{
    'description': '(mdp18) Wildlife Preserve:\n\nsubmitted by Fei Fang, Thanh Hong Nguyen and Thomas Keller.\n\nDescription: This domain is based on the papers : \n [1] Fei Fang, Peter Stone and Milind Tambe: "When Security Games Go Green: Designing Defender Strategies to Prevent Poaching and Illegal Fishing". IJCAI 2015.\n [2] Thanh H. Nguyen, Rong Yang, Amos Azaria, Sarit Kraus and Milind Tambe: "Analyzing the Effectiveness of Adversary Modeling in Security Games". AAAI 2013.\n The aim of the Wildlife Preserve domain is to protect a wildlife preserve from poachers by sending available ranger to areas. Poachers attack parts of the preserve depending on their preferences and an expectation where rangers will likely show up. This expectation is computed by exploiting the assumption typically taken in Stackelberg Security Games that the defender’s (i.e., rangers) mixed strategy is fully observed by the attacker, and memorized for a predefined number of steps.\n In each step, the planner obtains a reward for each area that has not been attacked undefended, and a penalty for each area that has. The challenge is to predict where poachers will attack with high probability and to lure the poachers that observe each step of the rangers into attacking an area where they are caught. A poacher that has been caught does not attack in the next step. ',
    'ipc': '2018',
    'name': 'wildlife-preserve',
    'problems': [('wildlife-preserve-mdp-2018/wildlife-preserve_01_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__01.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_02_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__02.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_03_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__03.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_04_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__04.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_05_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__05.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_06_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__06.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_07_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__07.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_08_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__08.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_09_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__09.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_10_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__10.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_11_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__11.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_12_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__12.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_13_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__13.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_14_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__14.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_15_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__15.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_16_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__16.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_17_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__17.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_18_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__18.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_19_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__19.rddl'),
                 ('wildlife-preserve-mdp-2018/wildlife-preserve_20_mdp.rddl', 'wildlife-preserve-mdp-2018/wildlife-preserve_inst_mdp__20.rddl')]}]
