domains = [{
    'description': '(mdp18) Chromatic Dice:\n\nsubmitted by Thomas Keller.\n\nDescription: Chromatic Dice is a variant of the popular dice game Yahtzee (also known as Kniffel). The most important difference is that dice show colored values upon rolling, where the color is independent from the value (e.g., the same die can come up with a blue 6 and a red 6 in two consecutive steps). The colors allow for some additional categories in a new middle section (one for each color where the sum of all values with a certain color count) and five new categories in the lower section (color versions of three and four of a kind, full house, flush and rainbow). Like the "upper" section (with categories ones, twos, etc), the new middle section allows for a bonus if the assigned dice meet certain criteria. Since this domain is modelled without integer-valued variables, we cannot encode a condition for the bonus that relies on the sum of all entries in the section (each entry is directly converted into immediate reward which cannot be accessed later). Instead, we take a probabilistic approach, where we keep track of levels that define a probability that the bonus is received. If four or five dice count towards one of the categories, the level increases, and if one or two dice count it is decreased. There is such a level both for the upper and middle section, and both boni are granted (or not) at the end of a run. Even though the optimal policy in the MDP version of Chromatic Dice that is considered here is not optimal in a version of the original problem (i.e., a game with one or more adversaries), it is close enough to make for a challenging player that is non-trivial to defeat.',
    'ipc': '2018',
    'name': 'chromatic-dice',
    'problems': [('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__01.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__02.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__03.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__04.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__05.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__06.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__07.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__08.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__09.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__10.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__11.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__12.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__13.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__14.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__15.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__16.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__17.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__18.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__19.rddl'),
                 ('chromatic-dice-mdp-2018/chromatic-dice_mdp.rddl', 'chromatic-dice-mdp-2018/chromatic-dice_inst_mdp__20.rddl')]}]
